# Jason Ficorilli | 6/26/2026

# CREDITS: dbt model code adapted from dbt Cloud quickstart template for BigQuery
# schema.yml descriptions and project directory structure adapted from Gemini output

name: "dim_skater_careers"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dim_skater_careers:
    # Applies to all files under models
    +materialized: table
